"colorscheme 0x7A69_dark
"colorscheme 1989
"colorscheme 256-grayvim
"colorscheme 256-jungle
"colorscheme 256_noir
"colorscheme 3dglasses
"colorscheme abbott
"colorscheme abra
"colorscheme adam
"colorscheme adaryn
"colorscheme adobe
"colorscheme adrian
"colorscheme advantage
"colorscheme af
"colorscheme aiseered
"colorscheme alduin
"colorscheme anderson
"colorscheme anotherdark
"colorscheme ansi_blows
"colorscheme antares
"colorscheme apprentice
"colorscheme aqua
"colorscheme argonaut
"colorscheme ashen
"colorscheme asmanian2
"colorscheme asmanian_blood
"colorscheme asmdev2
"colorscheme asmdev
"colorscheme astronaut
"colorscheme asu1dark   " LIKE
"colorscheme atom
"colorscheme aurora
"colorscheme automation
"colorscheme autumnleaf
"colorscheme autumn
"colorscheme babymate256
"colorscheme badwolf
"colorscheme bandit
"colorscheme base16-ateliercave
"colorscheme base16-atelierdune
"colorscheme base16-atelierestuary
"colorscheme base16-atelierforest
"colorscheme base16-atelierheath
"colorscheme base16-atelierlakeside
"colorscheme base16-atelierplateau
"colorscheme base16-ateliersavanna
"colorscheme base16-atelierseaside
"colorscheme base16-ateliersulphurpool
"colorscheme base16-railscasts
"colorscheme base
"colorscheme basic
"colorscheme baycomb
"colorscheme bayQua
"colorscheme bclear
"colorscheme beachcomber
"colorscheme beauty256
"colorscheme beekai
"colorscheme behelit
"colorscheme benlight
"colorscheme Benokai
"colorscheme bensday
"colorscheme billw
"colorscheme biogoo
"colorscheme birds-of-paradise
"colorscheme black_angus
"colorscheme blackbeauty
"colorscheme blackboard
"colorscheme blackdust
"colorscheme blacklight
"colorscheme BlackSea
"colorscheme Black
"colorscheme blaquemagick
"colorscheme blazer
"colorscheme blink
"colorscheme Blue2
"colorscheme bluechia
"colorscheme bluedrake
"colorscheme bluegreen
"colorscheme blueprint
"colorscheme blueshift
"colorscheme blue
"colorscheme bluez
"colorscheme blugrine
"colorscheme bmichaelsen
"colorscheme bocau
"colorscheme bog
"colorscheme borland
"colorscheme breeze
"colorscheme brogrammer
"colorscheme brookstream
"colorscheme brown
"colorscheme bubblegum-256-dark
"colorscheme bubblegum-256-light
"colorscheme bubblegum
"colorscheme buddy
"colorscheme burnttoast256
"colorscheme busierbee
"colorscheme busybee
"colorscheme buttercream
"colorscheme bvemu
"colorscheme bw
"colorscheme c16gui
"colorscheme C64
"colorscheme cabin
"colorscheme cake16
"colorscheme cake
"colorscheme calmar256-dark
"colorscheme calmar256-light
"colorscheme camo
"colorscheme campfire
"colorscheme candycode
"colorscheme candyman
"colorscheme CandyPaper
"colorscheme candy
"colorscheme caramel
"colorscheme carrot
"colorscheme carvedwoodcool
"colorscheme carvedwood
"colorscheme cascadia
"colorscheme cgpro
"colorscheme chance-of-storm
"colorscheme charged-256
"colorscheme charon
"colorscheme Chasing_Logic
"colorscheme chela_light
"colorscheme chlordane
"colorscheme ChocolateLiquor
"colorscheme ChocolatePapaya
"colorscheme chocolate
"colorscheme chrysoprase
"colorscheme clarity
"colorscheme cleanphp
"colorscheme cleanroom
"colorscheme clearance
"colorscheme cloudy
"colorscheme clue
"colorscheme cobalt2
"colorscheme cobaltish
"colorscheme cobalt
"colorscheme coda
"colorscheme codeblocks_dark
"colorscheme codeburn
"colorscheme CodeFactoryv3
"colorscheme codeschool
"colorscheme coffee
"colorscheme coldgreen
"colorscheme colorer
"colorscheme colorful256
"colorscheme colorful
"colorscheme colorsbox-faff
"colorscheme colorsbox-greenish
"colorscheme colorsbox-material
"colorscheme colorsbox-stblue
"colorscheme colorsbox-stbright
"colorscheme colorsbox-steighties
"colorscheme colorsbox-stnight
"colorscheme colorzone
"colorscheme contrasty
"colorscheme cool
"colorscheme corn
"colorscheme corporation
"colorscheme crayon
"colorscheme crt
"colorscheme cthulhian
"colorscheme custom
"colorscheme c
"colorscheme d8g_01
"colorscheme d8g_02
"colorscheme d8g_03
"colorscheme d8g_04
"colorscheme dante
"colorscheme Dark2
"colorscheme darkblack
"colorscheme darkblue2
"colorscheme darkblue
"colorscheme darkBlue
"colorscheme darkbone
"colorscheme darkburn
"colorscheme DarkDefault
"colorscheme darkdevel
"colorscheme darkdot
"colorscheme darkeclipse
"colorscheme darkerdesert
"colorscheme darker-robin
"colorscheme darkocean
"colorscheme darkrobot
"colorscheme dark-ruby
"colorscheme darkslategray
"colorscheme darkspectrum
"colorscheme darktango
"colorscheme Dark
"colorscheme darkzen
"colorscheme darkZ
"colorscheme darth
"colorscheme dawn
"colorscheme deepsea
"colorscheme default
"colorscheme delek
"colorscheme delphi
"colorscheme denim
"colorscheme derefined
"colorscheme desert256v2
"colorscheme desert256
"colorscheme desertedoceanburnt
"colorscheme desertedocean
"colorscheme desertEx
"colorscheme desertink
"colorscheme desert
"colorscheme detailed
"colorscheme devbox-dark-256
"colorscheme DevC++
"colorscheme Dev_Delight
"colorscheme deveiate
"colorscheme developer
"colorscheme Dim2
"colorscheme DimBlue
"colorscheme DimGreens
"colorscheme DimGreen
"colorscheme DimGrey
"colorscheme DimRed
"colorscheme DimSlate
"colorscheme Dim
"colorscheme disciple
"colorscheme distinguished
"colorscheme django
"colorscheme donbass
"colorscheme doorhinge
"colorscheme doriath
"colorscheme dracula
"colorscheme dual
"colorscheme dull
"colorscheme duotone-darkcave
"colorscheme duotone-darkdesert
"colorscheme duotone-darkearth
"colorscheme duotone-darkforest
"colorscheme duotone-darkheath
"colorscheme duotone-darklake
"colorscheme duotone-darkmeadow
"colorscheme duotone-darkpark
"colorscheme duotone-darkpool
"colorscheme duotone-darksea
"colorscheme duotone-darkspace
"colorscheme duotone-dark
"colorscheme dusk
"colorscheme dw_blue
"colorscheme dw_cyan
"colorscheme dw_green
"colorscheme dw_orange
"colorscheme dw_purple
"colorscheme dw_red
"colorscheme dw_yellow
"colorscheme earendel
"colorscheme earthburn
"colorscheme earth
"colorscheme eclipse
"colorscheme eclm_wombat
"colorscheme ecostation
"colorscheme editplus
"colorscheme edo_sea
"colorscheme ego
"colorscheme ekin
"colorscheme ekvoli
"colorscheme elda
"colorscheme elflord
"colorscheme elise
"colorscheme elisex
"colorscheme elrodeo
"colorscheme elrond
"colorscheme emacs
"colorscheme enigma
"colorscheme enzyme
"colorscheme erez
"colorscheme eva01
"colorscheme eva
"colorscheme evening1
"colorscheme evening
"colorscheme evolution
"colorscheme far
"colorscheme felipec
"colorscheme feral
"colorscheme flatcolor
"colorscheme flatlandia
"colorscheme flatland
"colorscheme flattened_dark
"colorscheme flattened_light
"colorscheme flattown
"colorscheme flattr
"colorscheme flatui
"colorscheme fnaqevan
"colorscheme fog
"colorscheme fokus
"colorscheme forneus
"colorscheme freya
"colorscheme frood
"colorscheme frozen
"colorscheme fruidle
"colorscheme fruit
"colorscheme fruity
"colorscheme fu
"colorscheme fx
"colorscheme gardener
"colorscheme gemcolors
"colorscheme genericdc-light
"colorscheme genericdc
"colorscheme gentooish
"colorscheme getafe
"colorscheme getfresh
"colorscheme github
"colorscheme gobo
"colorscheme golded
"colorscheme golden
"colorscheme goodwolf
"colorscheme google
"colorscheme gor
"colorscheme gotham256
"colorscheme gotham
"colorscheme gothic
"colorscheme grape
"colorscheme gravity
"colorscheme grayorange
"colorscheme graywh
"colorscheme grb256
"colorscheme greens
"colorscheme Green
"colorscheme greenvision
"colorscheme grey2
"colorscheme greyblue
"colorscheme grishin
"colorscheme gruvbox
"colorscheme gryffin
"colorscheme guardian
"colorscheme guepardo
"colorscheme h80
"colorscheme habiLight
"colorscheme harlequin
"colorscheme heliotrope
"colorscheme hemisu
"colorscheme herald
"colorscheme herokudoc-
"colorscheme herokudoc
"colorscheme heroku-terminal
"colorscheme heroku
"colorscheme hhazure
"colorscheme hhdblue
"colorscheme hhdcyan
"colorscheme hhdgray
"colorscheme hhdgreen
"colorscheme hhdmagenta
"colorscheme hhdred
"colorscheme hhdyellow
"colorscheme hhorange
"colorscheme hhpink
"colorscheme hhspring
"colorscheme hhteal
"colorscheme hhviolet
"colorscheme hilal
"colorscheme holokai
"colorscheme hornet
"colorscheme hotpot
"colorscheme hybrid-light
"colorscheme hybrid_material
"colorscheme hybrid_reverse
"colorscheme hybrid
"colorscheme iangenzo
"colorscheme ibmedit
"colorscheme icansee
"colorscheme iceberg
"colorscheme impactG
"colorscheme impactjs
"colorscheme impact
"colorscheme industrial
"colorscheme industry
"colorscheme ingretu
"colorscheme inkpot
"colorscheme inori
"colorscheme ir_black
"colorscheme ironman
"colorscheme itg_flat
"colorscheme jaime
"colorscheme jammy
"colorscheme janah
"colorscheme jelleybeans
"colorscheme jellybeans
"colorscheme jellyx
"colorscheme jhdark
"colorscheme jhlight
"colorscheme jiks
"colorscheme kalahari
"colorscheme kalisi
"colorscheme kaltex
"colorscheme kalt
"colorscheme kate
"colorscheme kellys
"colorscheme khaki
"colorscheme kib_darktango
"colorscheme kib_plastic
"colorscheme kiss
"colorscheme kkruby
"colorscheme koehler
"colorscheme kolor
"colorscheme kruby
"colorscheme kyle
"colorscheme laederon
"colorscheme landscape
"colorscheme lanzarotta
"colorscheme lapis256
"colorscheme last256
"colorscheme late_evening
"colorscheme lazarus
"colorscheme legiblelight
"colorscheme leglight2
"colorscheme leo
"colorscheme less
"colorscheme lettuce
"colorscheme leya
"colorscheme lightcolors
"colorscheme LightDefaultGrey
"colorscheme LightDefault
"colorscheme lightning
"colorscheme LightTan
"colorscheme Light
"colorscheme LightYellow
"colorscheme lilac
"colorscheme lilydjwg_dark
"colorscheme lilydjwg_green
"colorscheme lilypink
"colorscheme lingodirector
"colorscheme liquidcarbon
"colorscheme literal_tango
"colorscheme lizard256
"colorscheme lizard
"colorscheme lodestone
"colorscheme loogica
"colorscheme louver
"colorscheme lucid
"colorscheme lucius
"colorscheme luinnar
"colorscheme lumberjack
"colorscheme luna-term
"colorscheme luna
"colorscheme lxvc
"colorscheme mac_classic
"colorscheme made_of_code
"colorscheme madeofcode
"colorscheme magicwb
"colorscheme mango
"colorscheme manuscript
"colorscheme manxome
"colorscheme marklar
"colorscheme maroloccio2
"colorscheme maroloccio3
"colorscheme maroloccio
"colorscheme mars
"colorscheme martin_krischik
"colorscheme materialbox
"colorscheme material-theme
"colorscheme materialtheme
"colorscheme material
"colorscheme matrix
"colorscheme maui
"colorscheme mayansmoke
"colorscheme mdark
"colorscheme mellow
"colorscheme meta5
"colorscheme metacosm
"colorscheme midnight
"colorscheme miko
"colorscheme minimalist
"colorscheme mint
"colorscheme mizore
"colorscheme mod8
"colorscheme mod_tcsoft
"colorscheme mojave
"colorscheme molokai_dark
colorscheme molokai        "like
"colorscheme monoacc
"colorscheme monochrome
"colorscheme monokai-chris
"colorscheme monokain
"colorscheme Monokai
"colorscheme montz
"colorscheme moonshine_lowcontrast
"colorscheme moonshine
"colorscheme mophiaDark
"colorscheme mophiaSmoke
"colorscheme mopkai
"colorscheme moria
"colorscheme morning
"colorscheme moss
"colorscheme motus
"colorscheme MountainDew
"colorscheme mrkn256
"colorscheme mrpink
"colorscheme mud
"colorscheme muon
"colorscheme murphy
"colorscheme mushroom
"colorscheme mustang
"colorscheme native
"colorscheme nature
"colorscheme navajo-night
"colorscheme navajo
"colorscheme nazca
"colorscheme nedit2
"colorscheme nedit
"colorscheme nefertiti
"colorscheme neon
"colorscheme neonwave
"colorscheme nerv-ous
"colorscheme neutron
"colorscheme neverland2-darker
"colorscheme neverland2
"colorscheme neverland-darker
"colorscheme neverland
"colorscheme neverness
"colorscheme nevfn
"colorscheme newspaper
"colorscheme newsprint
"colorscheme nicotine
"colorscheme nightflight2
"colorscheme nightflight
"colorscheme nightshade_print
"colorscheme nightshade
"colorscheme nightshimmer
"colorscheme nightsky
"colorscheme night
"colorscheme night_vision
"colorscheme nightVision
"colorscheme nightwish
"colorscheme no_quarter
"colorscheme northland
"colorscheme northsky
"colorscheme norwaytoday
"colorscheme nour
"colorscheme nuvola
"colorscheme obsidian2
"colorscheme obsidian
"colorscheme oceanblack256
"colorscheme oceanblack
"colorscheme oceandeep
"colorscheme OceanicNext
"colorscheme oceanlight
"colorscheme olive
"colorscheme onedark
"colorscheme orange
"colorscheme osx_like
"colorscheme otaku
"colorscheme oxeded
"colorscheme pablo
"colorscheme pacific
"colorscheme paintbox
"colorscheme PapayaWhip
"colorscheme PaperColor
"colorscheme parsec
"colorscheme peachpuff
"colorscheme peaksea
"colorscheme pencil
"colorscheme penultimate
"colorscheme peppers
"colorscheme perfect
"colorscheme pf_earth
"colorscheme phd
"colorscheme phoenix
"colorscheme phphaxor
"colorscheme phpx
"colorscheme pink
"colorscheme playroom
"colorscheme pleasant
"colorscheme potts
"colorscheme predawn
"colorscheme preto
"colorscheme pride
"colorscheme primary
"colorscheme print_bw
"colorscheme prmths
"colorscheme professional
"colorscheme proton
"colorscheme ps_color
"colorscheme pspad
"colorscheme pt_black
"colorscheme putty
"colorscheme pw
"colorscheme pyte
"colorscheme python
"colorscheme quagmire
"colorscheme radicalgoodspeed
"colorscheme railscasts
"colorscheme rainbow_autumn
"colorscheme rainbow_fine_blue
"colorscheme rainbow_night
"colorscheme rainbow_sea
"colorscheme rakr-light
"colorscheme random
"colorscheme rastafari
"colorscheme rcg_gui
"colorscheme rcg_term
"colorscheme rdark-terminal
"colorscheme rdark
"colorscheme redblack
"colorscheme redstring
"colorscheme Red
"colorscheme refactor
"colorscheme relaxedgreen
"colorscheme reliable
"colorscheme reloaded
"colorscheme revolutions
"colorscheme Revolution
"colorscheme robinhood
"colorscheme ron
"colorscheme rootwater
"colorscheme sadek1
"colorscheme sand
"colorscheme sandydune
"colorscheme satori
"colorscheme saturn
"colorscheme scheakur
"colorscheme scite
"colorscheme scooby
"colorscheme sean
"colorscheme seashell
"colorscheme seattle
"colorscheme selenitic
"colorscheme seoul256-light
"colorscheme seoul256
"colorscheme seoul
"colorscheme seti
"colorscheme settlemyer
"colorscheme sexy-railscasts
"colorscheme sf
"colorscheme shadesofamber
"colorscheme shades-of-teal
"colorscheme shine
"colorscheme shobogenzo
"colorscheme sienna
"colorscheme sierra
"colorscheme sift
"colorscheme silent
"colorscheme simple256
"colorscheme simpleandfriendly
"colorscheme simple_b
"colorscheme simplewhite
"colorscheme simplon
"colorscheme skittles_berry
"colorscheme skittles_dark
"colorscheme sky
"colorscheme slate2
"colorscheme SlateDark
"colorscheme Slate
"colorscheme smpl
"colorscheme smp
"colorscheme smyck
"colorscheme soda
"colorscheme softbluev2
"colorscheme softblue
"colorscheme softlight
"colorscheme solarized
"colorscheme sole
"colorscheme sol-term
"colorscheme sol
"colorscheme sonofobsidian
"colorscheme sonoma
"colorscheme sorcerer
"colorscheme soruby
"colorscheme soso
"colorscheme sourcerer
"colorscheme southernlights
"colorscheme southwest-fog
"colorscheme spacegray      " like
"colorscheme spectro
"colorscheme spiderhawk
"colorscheme Spink
"colorscheme spring
"colorscheme sprinkles
"colorscheme stackoverflow
"colorscheme stingray
"colorscheme stonewashed-256
"colorscheme stonewashed-gui
"colorscheme strange
"colorscheme strawimodo
"colorscheme summerfruit256
"colorscheme summerfruit
"colorscheme sunburst
"colorscheme surveyor
"colorscheme swamplight
"colorscheme sweater
"colorscheme SweetCandy
"colorscheme symfony
"colorscheme synic
"colorscheme tabula
"colorscheme tango2
"colorscheme tango-desert
"colorscheme tango-morning
"colorscheme tangoshady
"colorscheme tango
"colorscheme tangoX
"colorscheme taqua
"colorscheme tayra
"colorscheme tchaba2
"colorscheme tchaba
"colorscheme tcsoft
"colorscheme telstar
"colorscheme termschool
"colorscheme tesla
"colorscheme tetragrammaton
"colorscheme textmate16
"colorscheme thegoodluck
"colorscheme thestars
"colorscheme thornbird
"colorscheme thor
"colorscheme tibet
"colorscheme tidy
"colorscheme tir_black
"colorscheme tolerable
"colorscheme tomatosoup
"colorscheme Tomorrow-Night-Blue
"colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme Tomorrow-Night
"colorscheme Tomorrow
"colorscheme tony_light
"colorscheme toothpik
"colorscheme torte
"colorscheme transparent
"colorscheme triplejelly
"colorscheme trivial256
"colorscheme trogdor
"colorscheme tropikos
"colorscheme turbo
"colorscheme tutticolori
"colorscheme twilight256
"colorscheme twilight
"colorscheme twitchy
"colorscheme two2tango
"colorscheme ubaryd
"colorscheme ubloh
"colorscheme umber-green
"colorscheme understated
"colorscheme underwater-mod
"colorscheme underwater
"colorscheme up
"colorscheme valloric
"colorscheme vanzan_color
"colorscheme vcbc
"colorscheme vc
"colorscheme vexorian
"colorscheme vibrantink             "like it
"colorscheme vilight
"colorscheme brant
"colorscheme visualstudio
"colorscheme vividchalk
"colorscheme VIvid
"colorscheme vj
"colorscheme void
"colorscheme vydark
"colorscheme vylight
"colorscheme wargrey
"colorscheme warm_grey
"colorscheme wasabi256
"colorscheme watermark
"colorscheme wellsokai
"colorscheme White2
"colorscheme whitebox
"colorscheme whitedust
"colorscheme white
"colorscheme widower
"colorscheme win9xblueback
"colorscheme wintersday
"colorscheme winter
"colorscheme woju
"colorscheme wolfpack
"colorscheme wombat256i
"colorscheme wombat256mod
"colorscheme wombat256
"colorscheme wombat
"colorscheme wood
"colorscheme wuye
"colorscheme xemacs
"colorscheme xian
"colorscheme xmaslights
"colorscheme xoria256
"colorscheme xterm16
"colorscheme yeller
"colorscheme zazen
"colorscheme zellner
"colorscheme zenburn
"colorscheme zenesque
"colorscheme zen
"colorscheme zephyr
"colorscheme zmrok
"colorscheme znake
