"colorscheme 0x7A69_dark
"colorscheme 1989
"colorscheme 256-grayvim
"colorscheme 256-jungle
"colorscheme 256_noir
"colorscheme 3dglasses
"colorscheme abbott
"colorscheme abra
"colorscheme adam
"colorscheme adaryn
"colorscheme adobe
"colorscheme adrian
"colorscheme advantage
"colorscheme af
"colorscheme aiseered
"colorscheme alduin
"colorscheme anderson
"colorscheme anotherdark
"colorscheme ansi_blows
"colorscheme antares
"colorscheme apprentice
"colorscheme aqua
"colorscheme argonaut
"colorscheme ashen
"colorscheme asmanian2
"colorscheme asmanian_blood
"colorscheme asmdev
"colorscheme asmdev2
"colorscheme astronaut
"colorscheme asu1dark   " LIKE
"colorscheme atom
"colorscheme aurora
"colorscheme automation
"colorscheme autumn
"colorscheme autumnleaf
"colorscheme babymate256
"colorscheme badwolf
"colorscheme bandit
"colorscheme base
"colorscheme base16-ateliercave
"colorscheme base16-atelierdune
"colorscheme base16-atelierestuary
"colorscheme base16-atelierforest
"colorscheme base16-atelierheath
"colorscheme base16-atelierlakeside
"colorscheme base16-atelierplateau
"colorscheme base16-ateliersavanna
"colorscheme base16-atelierseaside
"colorscheme base16-ateliersulphurpool
"colorscheme base16-railscasts
"colorscheme basic
"colorscheme baycomb
"colorscheme bayQua
"colorscheme bclear
"colorscheme beachcomber
"colorscheme beauty256
"colorscheme beekai
"colorscheme behelit
"colorscheme benlight
"colorscheme Benokai
"colorscheme bensday
"colorscheme billw
"colorscheme biogoo
"colorscheme birds-of-paradise
"colorscheme Black
"colorscheme black_angus
"colorscheme blackbeauty
"colorscheme blackboard
"colorscheme blackdust
"colorscheme blacklight
"colorscheme BlackSea
"colorscheme blaquemagick
"colorscheme blazer
"colorscheme blink
"colorscheme blue
"colorscheme Blue2
"colorscheme bluechia
"colorscheme bluedrake
"colorscheme bluegreen
"colorscheme blueprint
"colorscheme blueshift
"colorscheme bluez
"colorscheme blugrine
"colorscheme bmichaelsen
"colorscheme bocau
"colorscheme bog
"colorscheme borland
"colorscheme brant
"colorscheme breeze
"colorscheme brogrammer
"colorscheme brookstream
"colorscheme brown
"colorscheme bubblegum
"colorscheme bubblegum-256-dark
"colorscheme bubblegum-256-light
"colorscheme buddy
"colorscheme burnttoast256
"colorscheme busierbee
"colorscheme busybee
"colorscheme buttercream
"colorscheme bvemu
"colorscheme bw
"colorscheme c
"colorscheme c16gui
"colorscheme C64
"colorscheme cabin
"colorscheme cake
"colorscheme cake16
"colorscheme calmar256-dark
"colorscheme calmar256-light
"colorscheme camo
"colorscheme campfire
"colorscheme candy
"colorscheme candycode
"colorscheme candyman
"colorscheme CandyPaper
"colorscheme caramel
"colorscheme carrot
"colorscheme carvedwood
"colorscheme carvedwoodcool
"colorscheme cascadia
"colorscheme cgpro
"colorscheme chance-of-storm
"colorscheme charged-256
"colorscheme charon
"colorscheme Chasing_Logic
"colorscheme chela_light
"colorscheme chlordane
"colorscheme chocolate
"colorscheme ChocolateLiquor
"colorscheme ChocolatePapaya
"colorscheme chrysoprase
"colorscheme clarity
"colorscheme cleanphp
"colorscheme cleanroom
"colorscheme clearance
"colorscheme cloudy
"colorscheme clue
"colorscheme cobalt
"colorscheme cobalt2
"colorscheme cobaltish
"colorscheme coda
"colorscheme codeblocks_dark
"colorscheme codeburn
"colorscheme CodeFactoryv3
"colorscheme codeschool
"colorscheme coffee
"colorscheme coldgreen
"colorscheme colorer
"colorscheme colorful
"colorscheme colorful256
"colorscheme colorsbox-faff
"colorscheme colorsbox-greenish
"colorscheme colorsbox-material
"colorscheme colorsbox-stblue
"colorscheme colorsbox-stbright
"colorscheme colorsbox-steighties
"colorscheme colorsbox-stnight
"colorscheme colorzone
"colorscheme contrasty
"colorscheme cool
"colorscheme corn
"colorscheme corporation
"colorscheme crayon
"colorscheme crt
"colorscheme cthulhian
"colorscheme custom
"colorscheme d8g_01
"colorscheme d8g_02
"colorscheme d8g_03
"colorscheme d8g_04
"colorscheme dante
"colorscheme Dark
"colorscheme Dark2
"colorscheme darkblack
"colorscheme darkblue
"colorscheme darkBlue
"colorscheme darkblue2
"colorscheme darkbone
"colorscheme darkburn
"colorscheme DarkDefault
"colorscheme darkdevel
"colorscheme darkdot
"colorscheme darkeclipse
"colorscheme darkerdesert
"colorscheme darker-robin
"colorscheme darkocean
"colorscheme darkrobot
"colorscheme dark-ruby
"colorscheme darkslategray
"colorscheme darkspectrum
"colorscheme darktango
"colorscheme darkZ
"colorscheme darkzen
"colorscheme darth
"colorscheme dawn
"colorscheme deepsea
"colorscheme default
"colorscheme delek
"colorscheme delphi
"colorscheme denim
"colorscheme derefined
"colorscheme desert
"colorscheme desert256
"colorscheme desert256v2
"colorscheme desertedocean
"colorscheme desertedoceanburnt
"colorscheme desertEx
"colorscheme desertink
"colorscheme detailed
"colorscheme devbox-dark-256
"colorscheme DevC++
"colorscheme Dev_Delight
"colorscheme deveiate
"colorscheme developer
"colorscheme Dim
"colorscheme Dim2
"colorscheme DimBlue
"colorscheme DimGreen
"colorscheme DimGreens
"colorscheme DimGrey
"colorscheme DimRed
"colorscheme DimSlate
"colorscheme disciple
"colorscheme distinguished
"colorscheme django
"colorscheme donbass
"colorscheme doorhinge
"colorscheme doriath
"colorscheme dracula
"colorscheme dual
"colorscheme dull
"colorscheme duotone-dark
"colorscheme duotone-darkcave
"colorscheme duotone-darkdesert
"colorscheme duotone-darkearth
"colorscheme duotone-darkforest
"colorscheme duotone-darkheath
"colorscheme duotone-darklake
"colorscheme duotone-darkmeadow
"colorscheme duotone-darkpark
"colorscheme duotone-darkpool
"colorscheme duotone-darksea
"colorscheme duotone-darkspace
"colorscheme dusk
"colorscheme dw_blue
"colorscheme dw_cyan
"colorscheme dw_green
"colorscheme dw_orange
"colorscheme dw_purple
"colorscheme dw_red
"colorscheme dw_yellow
"colorscheme earendel
"colorscheme earth
"colorscheme earthburn
"colorscheme eclipse
"colorscheme eclm_wombat
"colorscheme ecostation
"colorscheme editplus
"colorscheme edo_sea
"colorscheme ego
"colorscheme ekin
"colorscheme ekvoli
"colorscheme elda
"colorscheme elflord
"colorscheme elise
"colorscheme elisex
"colorscheme elrodeo
"colorscheme elrond
"colorscheme emacs
"colorscheme enigma
"colorscheme enzyme
"colorscheme erez
"colorscheme eva
"colorscheme eva01
"colorscheme evening
"colorscheme evening1
"colorscheme evolution
"colorscheme far
"colorscheme felipec
"colorscheme feral
"colorscheme flatcolor
"colorscheme flatland
"colorscheme flatlandia
"colorscheme flattened_dark
"colorscheme flattened_light
"colorscheme flattown
"colorscheme flattr
"colorscheme flatui
"colorscheme fnaqevan
"colorscheme fog
"colorscheme fokus
"colorscheme forneus
"colorscheme freya
"colorscheme frood
"colorscheme frozen
"colorscheme fruidle
"colorscheme fruit
"colorscheme fruity
"colorscheme fu
"colorscheme fx
"colorscheme gardener
"colorscheme gemcolors
"colorscheme genericdc
"colorscheme genericdc-light
"colorscheme gentooish
"colorscheme getafe
"colorscheme getfresh
"colorscheme github
"colorscheme gobo
"colorscheme golded
"colorscheme golden
"colorscheme goodwolf
"colorscheme google
"colorscheme gor
"colorscheme gotham
"colorscheme gotham256
"colorscheme gothic
"colorscheme grape
"colorscheme gravity
"colorscheme grayorange
"colorscheme graywh
"colorscheme grb256
"colorscheme Green
"colorscheme greens
"colorscheme greenvision
"colorscheme grey2
"colorscheme greyblue
"colorscheme grishin
"colorscheme gruvbox
"colorscheme gryffin
"colorscheme guardian
"colorscheme guepardo
"colorscheme h80
"colorscheme habiLight
"colorscheme harlequin
"colorscheme heliotrope
"colorscheme hemisu
"colorscheme herald
"colorscheme heroku
"colorscheme herokudoc
"colorscheme herokudoc-
"colorscheme heroku-terminal
"colorscheme hhazure
"colorscheme hhdblue
"colorscheme hhdcyan
"colorscheme hhdgray
"colorscheme hhdgreen
"colorscheme hhdmagenta
"colorscheme hhdred
"colorscheme hhdyellow
"colorscheme hhorange
"colorscheme hhpink
"colorscheme hhspring
"colorscheme hhteal
"colorscheme hhviolet
"colorscheme hilal
"colorscheme holokai
"colorscheme hornet
"colorscheme hotpot
"colorscheme hybrid
"colorscheme hybrid-light
"colorscheme hybrid_material
"colorscheme hybrid_reverse
"colorscheme iangenzo
"colorscheme ibmedit
"colorscheme icansee
"colorscheme iceberg
"colorscheme impact
"colorscheme impactG
"colorscheme impactjs
"colorscheme industrial
"colorscheme industry
"colorscheme ingretu
"colorscheme inkpot
"colorscheme inori
"colorscheme ir_black
"colorscheme ironman
"colorscheme itg_flat
"colorscheme jaime
"colorscheme jammy
"colorscheme janah
"colorscheme jelleybeans
"colorscheme jellybeans
"colorscheme jellyx
"colorscheme jhdark
"colorscheme jhlight
"colorscheme jiks
"colorscheme kalahari
"colorscheme kalisi
"colorscheme kalt
"colorscheme kaltex
"colorscheme kate
"colorscheme kellys
"colorscheme khaki
"colorscheme kib_darktango
"colorscheme kib_plastic
"colorscheme kiss
"colorscheme kkruby
"colorscheme koehler
"colorscheme kolor
"colorscheme kruby
"colorscheme kyle
"colorscheme laederon
"colorscheme landscape
"colorscheme lanzarotta
"colorscheme lapis256
"colorscheme last256
"colorscheme late_evening
"colorscheme lazarus
"colorscheme legiblelight
"colorscheme leglight2
"colorscheme leo
"colorscheme less
"colorscheme lettuce
"colorscheme leya
"colorscheme Light
"colorscheme lightcolors
"colorscheme LightDefault
"colorscheme LightDefaultGrey
"colorscheme lightning
"colorscheme LightTan
"colorscheme LightYellow
"colorscheme lilac
"colorscheme lilydjwg_dark
"colorscheme lilydjwg_green
"colorscheme lilypink
"colorscheme lingodirector
"colorscheme liquidcarbon
"colorscheme literal_tango
"colorscheme lizard
"colorscheme lizard256
"colorscheme lodestone
"colorscheme loogica
"colorscheme louver
"colorscheme lucid
"colorscheme lucius
"colorscheme luinnar
"colorscheme lumberjack
"colorscheme luna
"colorscheme luna-term
"colorscheme lxvc
"colorscheme mac_classic
"colorscheme made_of_code
"colorscheme madeofcode
"colorscheme magicwb
"colorscheme mango
"colorscheme manuscript
"colorscheme manxome
"colorscheme marklar
"colorscheme maroloccio
"colorscheme maroloccio2
"colorscheme maroloccio3
"colorscheme mars
"colorscheme martin_krischik
"colorscheme material
"colorscheme materialbox
"colorscheme material-theme
"colorscheme materialtheme
"colorscheme matrix
"colorscheme maui
"colorscheme mayansmoke
"colorscheme mdark
"colorscheme mellow
"colorscheme meta5
"colorscheme metacosm
"colorscheme midnight
"colorscheme miko
"colorscheme minimalist
"colorscheme mint
"colorscheme mizore
"colorscheme mod8
"colorscheme mod_tcsoft
"colorscheme mojave
"colorscheme molokai_dark
colorscheme molokai        "like
"colorscheme monoacc
"colorscheme monochrome
"colorscheme Monokai
"colorscheme monokai-chris
"colorscheme monokain
"colorscheme montz
"colorscheme moonshine
"colorscheme moonshine_lowcontrast
"colorscheme mophiaDark
"colorscheme mophiaSmoke
"colorscheme mopkai
"colorscheme moria
"colorscheme morning
"colorscheme moss
"colorscheme motus
"colorscheme MountainDew
"colorscheme mrkn256
"colorscheme mrpink
"colorscheme mud
"colorscheme muon
"colorscheme murphy
"colorscheme mushroom
"colorscheme mustang
"colorscheme native
"colorscheme nature
"colorscheme navajo
"colorscheme navajo-night
"colorscheme nazca
"colorscheme nedit
"colorscheme nedit2
"colorscheme nefertiti
"colorscheme neon
"colorscheme neonwave
"colorscheme nerv-ous
"colorscheme neutron
"colorscheme neverland
"colorscheme neverland2
"colorscheme neverland2-darker
"colorscheme neverland-darker
"colorscheme neverness
"colorscheme nevfn
"colorscheme newspaper
"colorscheme newsprint
"colorscheme nicotine
"colorscheme night
"colorscheme nightflight
"colorscheme nightflight2
"colorscheme nightshade
"colorscheme nightshade_print
"colorscheme nightshimmer
"colorscheme nightsky
"colorscheme night_vision
"colorscheme nightVision
"colorscheme nightwish
"colorscheme no_quarter
"colorscheme northland
"colorscheme northsky
"colorscheme norwaytoday
"colorscheme nour
"colorscheme nuvola
"colorscheme obsidian
"colorscheme obsidian2
"colorscheme oceanblack
"colorscheme oceanblack256
"colorscheme oceandeep
"colorscheme OceanicNext
"colorscheme oceanlight
"colorscheme olive
"colorscheme onedark
"colorscheme orange
"colorscheme osx_like
"colorscheme otaku
"colorscheme oxeded
"colorscheme pablo
"colorscheme pacific
"colorscheme paintbox
"colorscheme PapayaWhip
"colorscheme PaperColor
"colorscheme parsec
"colorscheme peachpuff
"colorscheme peaksea
"colorscheme pencil
"colorscheme penultimate
"colorscheme peppers
"colorscheme perfect
"colorscheme pf_earth
"colorscheme phd
"colorscheme phoenix
"colorscheme phphaxor
"colorscheme phpx
"colorscheme pink
"colorscheme playroom
"colorscheme pleasant
"colorscheme potts
"colorscheme predawn
"colorscheme preto
"colorscheme pride
"colorscheme primary
"colorscheme print_bw
"colorscheme prmths
"colorscheme professional
"colorscheme proton
"colorscheme ps_color
"colorscheme pspad
"colorscheme pt_black
"colorscheme putty
"colorscheme pw
"colorscheme pyte
"colorscheme python
"colorscheme quagmire
"colorscheme radicalgoodspeed
"colorscheme railscasts
"colorscheme rainbow_autumn
"colorscheme rainbow_fine_blue
"colorscheme rainbow_night
"colorscheme rainbow_sea
"colorscheme rakr-light
"colorscheme random
"colorscheme rastafari
"colorscheme rcg_gui
"colorscheme rcg_term
"colorscheme rdark
"colorscheme rdark-terminal
"colorscheme Red
"colorscheme redblack
"colorscheme redstring
"colorscheme refactor
"colorscheme relaxedgreen
"colorscheme reliable
"colorscheme reloaded
"colorscheme Revolution
"colorscheme revolutions
"colorscheme robinhood
"colorscheme ron
"colorscheme rootwater
"colorscheme sadek1
"colorscheme sand
"colorscheme sandydune
"colorscheme satori
"colorscheme saturn
"colorscheme scheakur
"colorscheme scite
"colorscheme scooby
"colorscheme sean
"colorscheme seashell
"colorscheme seattle
"colorscheme selenitic
"colorscheme seoul
"colorscheme seoul256
"colorscheme seoul256-light
"colorscheme seti
"colorscheme settlemyer
"colorscheme sexy-railscasts
"colorscheme sf
"colorscheme shadesofamber
"colorscheme shades-of-teal
"colorscheme shine
"colorscheme shobogenzo
"colorscheme sienna
"colorscheme sierra
"colorscheme sift
"colorscheme silent
"colorscheme simple256
"colorscheme simpleandfriendly
"colorscheme simple_b
"colorscheme simplewhite
"colorscheme simplon
"colorscheme skittles_berry
"colorscheme skittles_dark
"colorscheme sky
"colorscheme Slate
"colorscheme slate2
"colorscheme SlateDark
"colorscheme smp
"colorscheme smpl
"colorscheme smyck
"colorscheme soda
"colorscheme softblue
"colorscheme softbluev2
"colorscheme softlight
"colorscheme sol
"colorscheme solarized
"colorscheme sole
"colorscheme sol-term
"colorscheme sonofobsidian
"colorscheme sonoma
"colorscheme sorcerer
"colorscheme soruby
"colorscheme soso
"colorscheme sourcerer
"colorscheme southernlights
"colorscheme southwest-fog
"colorscheme spacegray      " like
"colorscheme spectro
"colorscheme spiderhawk
"colorscheme Spink
"colorscheme spring
"colorscheme sprinkles
"colorscheme stackoverflow
"colorscheme stingray
"colorscheme stonewashed-256
"colorscheme stonewashed-gui
"colorscheme strange
"colorscheme strawimodo
"colorscheme summerfruit
"colorscheme summerfruit256
"colorscheme sunburst
"colorscheme surveyor
"colorscheme swamplight
"colorscheme sweater
"colorscheme SweetCandy
"colorscheme symfony
"colorscheme synic
"colorscheme tabula
"colorscheme tango
"colorscheme tango2
"colorscheme tango-desert
"colorscheme tango-morning
"colorscheme tangoshady
"colorscheme tangoX
"colorscheme taqua
"colorscheme tayra
"colorscheme tchaba
"colorscheme tchaba2
"colorscheme tcsoft
"colorscheme telstar
"colorscheme termschool
"colorscheme tesla
"colorscheme tetragrammaton
"colorscheme textmate16
"colorscheme thegoodluck
"colorscheme thestars
"colorscheme thor
"colorscheme thornbird
"colorscheme tibet
"colorscheme tidy
"colorscheme tir_black
"colorscheme tolerable
"colorscheme tomatosoup
"colorscheme Tomorrow
"colorscheme Tomorrow-Night
"colorscheme Tomorrow-Night-Blue
"colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme tony_light
"colorscheme toothpik
"colorscheme torte
"colorscheme transparent
"colorscheme triplejelly
"colorscheme trivial256
"colorscheme trogdor
"colorscheme tropikos
"colorscheme turbo
"colorscheme tutticolori
"colorscheme twilight
"colorscheme twilight256
"colorscheme twitchy
"colorscheme two2tango
"colorscheme ubaryd
"colorscheme ubloh
"colorscheme umber-green
"colorscheme understated
"colorscheme underwater
"colorscheme underwater-mod
"colorscheme up
"colorscheme valloric
"colorscheme vanzan_color
"colorscheme vc
"colorscheme vcbc
"colorscheme vexorian
"colorscheme vibrantink             "like it
"colorscheme vilight
"colorscheme visualstudio
"colorscheme VIvid
"colorscheme vividchalk
"colorscheme vj
"colorscheme void
"colorscheme vydark
"colorscheme vylight
"colorscheme wargrey
"colorscheme warm_grey
"colorscheme wasabi256
"colorscheme watermark
"colorscheme wellsokai
"colorscheme white
"colorscheme White2
"colorscheme whitebox
"colorscheme whitedust
"colorscheme widower
"colorscheme win9xblueback
"colorscheme winter
"colorscheme wintersday
"colorscheme woju
"colorscheme wolfpack
"colorscheme wombat
"colorscheme wombat256
"colorscheme wombat256i
"colorscheme wombat256mod
"colorscheme wood
"colorscheme wuye
"colorscheme xemacs
"colorscheme xian
"colorscheme xmaslights
"colorscheme xoria256
"colorscheme xterm16
"colorscheme yeller
"colorscheme zazen
"colorscheme zellner
"colorscheme zen
"colorscheme zenburn
"colorscheme zenesque
"colorscheme zephyr
"colorscheme zmrok
"colorscheme znake
