#!/bin/bash -
#=======================================================================
#
#          FILE: which
#
#         USAGE: ./which
#
#   DESCRIPTION: Get Makefile to exit for certain recipes if `pipenv' is
#                not installed as they would only cause further errors
#                later.
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: This script aims to follow Google's `Shell Style Guide'
#                https://google.github.io/styleguide/shellguide.html
#        AUTHOR: Stephen Whitlock (jshwi), stephen@jshwisolutions.com
#  ORGANIZATION: Jshwi Solutions
#       CREATED: 08/09/20 10:58:32
#      REVISION: 1.0.0
#
# shellcheck disable=SC1090
#=======================================================================
source "$HOME/.dotfiles/lib/dotsh/lib.sh"

which-pipenv "$@" || exit 1
