# shellcheck source=/dev/null

# --- ENV ---
DOTFILES="$HOME/.dotfiles"
DOTFILES_SRC="$DOTFILES/src"
ZSH_DIR="$DOTFILES_SRC/zsh"
ZSHRC_CONFIG="$ZSH_DIR/zshrc.d"
ZSH_BASH_COMPAT="$ZSHRC_CONFIG/zshrc.bash_compat"

source "$ZSH_BASH_COMPAT"

# --- ZSTYLE ---
zstyle :compinstall filename "$ZSHRC"
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:killall:*'   force-list always
zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'


# --- TERMINAL DEFAULTS ---
setopt autocd
setopt correctall
unsetopt BEEP
autoload -U promptinit && promptinit  # command prompt
autoload -Uz compinit && compinit  # advanced tab-completion

# --- LOAD SETTINGS ---
source "$ZSH/oh-my-zsh.sh"
